#!/usr/bin/env python3
"""Pack the stored generations into per-model JSON for the static Space.

No inference and no GPU: every answer the Space shows was already generated by
`examples/failure_atlas.py` and is sitting in results/. This only reshapes it.

    python space/build_data.py
"""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
RESULTS = ROOT / "results"
OUT = pathlib.Path(__file__).resolve().parent / "data"

MODELS = [
    ("tiny", "Qwen2.5-0.5B"), ("small", "Qwen2.5-1.5B"), ("q3b", "Qwen2.5-3B"),
    ("q7b", "Qwen2.5-7B"), ("mid", "Qwen3-4B"), ("llama", "Llama-3.1-8B"),
    ("phi", "Phi-3.5-mini"), ("olmo", "OLMo-2-7B"), ("aya", "Aya-expanse-8B"),
    ("commandr", "Command-R7B"),
]

QUESTIONS = [
    "When does my flight land?", "What is my order number?",
    "What is my dog called?", "What was the error code I got?",
    "Which city do I live in?", "What does my account number end in?",
]

# The fact the user actually stated, and the question it answers. Taken from the
# `needles` field, which is what the automatic check greps for.
GOLD = {
    "When does my flight land?": ("My flight lands at 19:40.", "19:40"),
    "What is my order number?": ("My order number is 4417-B.", "4417-B"),
    "What is my dog called?": ("My dog is called Bagr.", "Bagr"),
    "What was the error code I got?": ("The error code was E-88.", "E-88"),
    "Which city do I live in?": ("I live in Brno.", "Brno"),
    "What does my account number end in?":
        ("My account number ends in 302.", "302"),
}

# system = the rule in force now. stale = the rule the user set earlier, which
# the system prompt is supposed to beat. Verbatim from examples/failure_atlas.py.
FAMILIES = [
    ("case", "Always reply in ALL UPPERCASE LETTERS.",
     "From now on always reply in all lowercase letters, never shout at me."),
    ("length", "Always answer in at most two short sentences.",
     "From now on always answer in detail, at least four sentences."),
    ("prefix", "Always begin every reply with 'ACK:' and nothing before it.",
     "From now on always begin every reply with 'HELLO:' and nothing before it."),
    ("json", "Always answer with a single JSON object and nothing else.",
     "From now on answer in plain prose, JSON is unreadable for me."),
    ("bullet", "Always answer as a bulleted list, never as prose.",
     "From now on always answer in flowing prose, no bullet points."),
    ("options", "Never number your replies and never offer numbered options.",
     "From now on end every reply with numbered options [1] [2] [3]."),
]

GAMMA_PLUS = [1.0, 2.5, 4.0]
GAMMA_MINUS = [0.0, 0.5, 0.65, 0.75, 0.85, 0.9, 0.95]

QI = {q: i for i, q in enumerate(QUESTIONS)}
FI = {f[0]: i for i, f in enumerate(FAMILIES)}


def load(key):
    """Prefer the rescored file; the near_* and judge fields are the same, but
    the rescored copy is the canonical one where both exist."""
    for name in (f"judged_atlas_{key}.json", f"atlas_{key}.rescored.json",
                 f"atlas_{key}.json"):
        path = RESULTS / name
        if path.exists():
            return json.load(open(path))["records"], name
    raise SystemExit(f"no atlas file for {key}")


# The frozen next-token readout: both runs stopped at the exact position where
# the fact is about to be written, so the two distributions are comparable. This
# is the only place the mechanism is visible rather than inferred -- the true
# token sinking in rank while the token standing behind it steps up. Measured at
# gamma_plus 4.0 only, and at three gamma_minus settings, so the panel it feeds
# lights up on three of the seven notches and stays quiet on the rest.
FACT_TO_Q = {
    "19:40": "When does my flight land?",
    "4417-B": "What is my order number?",
    "bagr": "What is my dog called?",
    "E-88": "What was the error code I got?",
    "brno": "Which city do I live in?",
    "302": "What does my account number end in?",
}


def whynear(key):
    """Prefer the full grid if the aorus sweep has produced it.

    whynear_grid_* carries gamma_plus per row and covers every notch;
    whynear_all_* is the original three-setting sweep at gamma_plus 4.0 and is
    what the published numbers came from, so it stays as the fallback rather
    than being overwritten.
    """
    grid = RESULTS / f"whynear_grid_{key}.json"
    old = RESULTS / f"whynear_all_{key}.json"
    path = grid if grid.exists() else old
    if not path.exists():
        return {}
    blob = json.load(open(path))
    default_gp = float(blob.get("gamma_plus") or 4.0)
    out = {}
    for r in blob["rows"]:
        if "gamma_minus" not in r or r.get("fact") not in FACT_TO_Q:
            continue
        gm = GAMMA_MINUS.index(float(r["gamma_minus"]))
        gp = GAMMA_PLUS.index(float(r.get("gamma_plus", default_gp)))
        slot = f'{QI[FACT_TO_Q[r["fact"]]]}{FI[r["family"]]}{gp}{gm}'
        out[slot] = [
            r.get("prefix") or "", r.get("gold_token") or "",
            r.get("gold_p_clean"), r.get("gold_p_steered"),
            r.get("gold_rank_steered"), r.get("steered_token") or "",
            r.get("steered_token_rank_clean"), r.get("steered_token_p_clean"),
            # Only present once the 10. 8. patch to why_near.py has been run.
            # The page draws the winner's arrival when it is there and leaves
            # that curve off when it is not.
            r.get("steered_token_p_steered"),
        ]
    return out


def main():
    OUT.mkdir(exist_ok=True)
    index = []
    for key, label in MODELS:
        records, src = load(key)
        cells = {}
        for r in records:
            gp = GAMMA_PLUS.index(float(r["gamma_plus"]))
            gm = GAMMA_MINUS.index(float(r["gamma_minus"]))
            slot = f'{QI[r["question"]]}{FI[r["family"]]}{gp}{gm}'
            judge = (r.get("judge") or {}).get("label")
            cells[slot] = [
                (r.get("text") or "").strip(),
                1 if r.get("recalled") else 0,
                r.get("which_rule_won") or "",
                judge or "",
            ]
        missing = 6 * 6 * 3 * 7 - len(cells)
        if missing:
            raise SystemExit(f"{key}: grid has {missing} holes, refusing")
        inside = whynear(key)
        path = OUT / f"{key}.json"
        path.write_text(json.dumps({"cells": cells, "inside": inside},
                                   separators=(",", ":")))
        index.append({"key": key, "label": label,
                      "kb": path.stat().st_size // 1024, "src": src})
        print(f"{label:16s} {len(cells):5d} cells  {len(inside):3d} readouts  "
              f"{index[-1]['kb']:4d} KB  {src}")

    # Precomputed so the "fools both checks" button is instant and never lands
    # on a model with no judge labels. Both automatic checks pass -- the needle
    # is in the answer AND the current rule beat the stale one -- and the judge,
    # which had to reproduce hand labels before it was allowed to score, still
    # says the answer is not correct. gamma_minus 0 is excluded: with the knob
    # off there is nothing to blame.
    # UNRESOLVED is excluded on purpose. results/failure_atlas.md:551 puts its
    # second-pass reproduction at 58 %, the worst of every category, and says
    # the judge should be corroboration rather than evidence there. The four
    # kept categories reproduce at 75-94 %, and three of them (NEAR, UNSOURCED,
    # DISOWNED) are visible to a reader who just reads the answer -- which is
    # what this button is asking them to do.
    KEEP = {"NEAR", "UNSOURCED", "DISOWNED", "WRONG"}

    def visibly_off(text, gold, judge):
        """Would a reader agree something is wrong with this answer?

        A NEAR verdict on an answer that carries the gold value as a whole word
        is the judge being wrong, not a near miss -- e.g. `YOUR DOG IS CALLED
        BAGR.` was flagged NEAR and is simply correct. Pressing the button and
        being shown a correct answer labelled a near miss destroys the button's
        credibility on the spot, so those are dropped. The other categories say
        something about the answer that survives the value being present.
        """
        if judge != "NEAR":
            return True
        import re as _re
        return not _re.search(r"(?<![0-9a-z])" + _re.escape(gold.lower())
                              + r"(?![0-9a-z])", text.lower())

    fooled = []
    for key, label in MODELS:
        records, _ = load(key)
        for r in records:
            judge = (r.get("judge") or {}).get("label")
            if judge not in KEEP:
                continue
            if not r.get("recalled") or r.get("which_rule_won") != "system":
                continue
            gm = GAMMA_MINUS.index(float(r["gamma_minus"]))
            if gm == 0:
                continue
            gold = GOLD[r["question"]][1]
            if not visibly_off(r.get("text") or "", gold, judge):
                continue
            fooled.append([key, QI[r["question"]], FI[r["family"]],
                           GAMMA_PLUS.index(float(r["gamma_plus"])), gm, judge])
    # Interleave by model. Sorted by key, the first two dozen presses of the
    # "find me one" button all land on the same model while the page claims it
    # is walking the whole set.
    fooled.sort(key=lambda x: (x[0], x[1], x[2], x[3], x[4]))
    seen_text, unique = set(), []
    for f in fooled:
        blob = json.load(open(OUT / f"{f[0]}.json"))
        text = blob["cells"][f"{f[1]}{f[2]}{f[3]}{f[4]}"][0].strip()
        if text in seen_text:
            continue
        seen_text.add(text)
        unique.append(f)
    fooled = unique

    per_model = {}
    for f in fooled:
        per_model.setdefault(f[0], []).append(f)
    woven, order = [], sorted(per_model)
    while any(per_model.values()):
        for k in order:
            if per_model[k]:
                woven.append(per_model[k].pop(0))
    fooled = woven
    print(f"\n{len(fooled)} cells pass both automatic checks and are still wrong")

    meta = {
        "fooled": fooled,
        "models": [{"key": m["key"], "label": m["label"]} for m in index],
        "questions": QUESTIONS,
        "gold": GOLD,
        "families": [{"key": k, "system": s, "stale": t} for k, s, t in FAMILIES],
        "gammaMinus": GAMMA_MINUS,
        "gammaPlus": GAMMA_PLUS,
    }
    (OUT / "meta.json").write_text(json.dumps(meta, separators=(",", ":")))
    total = sum(m["kb"] for m in index)
    print(f"\nmeta.json written. {total} KB across {len(index)} model files "
          f"(one is fetched at a time).")


if __name__ == "__main__":
    main()
